import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import ReduxProvider from '@/store/ReduxProvider';
import { Nav } from '@/components/Nav/Nav';
import styles from '../page.module.css';
import Search from '@/components/Search/Search';
import Sidebar from '@/components/Sidebar/Sidebar';

const inter = Inter({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <div className={styles.wrapper}>
        <div className={styles.container}>
          <main className={styles.main}>
            <Nav />
            <div className={styles.mainCenterblock}>
              <Search />
              {children}
            </div>
            <Sidebar />
          </main>
        </div>
      </div>
    </ReduxProvider>
  );
}
