import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/store/ReduxProvider';
import styles from './page.module.css';

const inter = Montserrat({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <ReduxProvider>
        <body className={inter.className}>
          <div className={styles.wrapper}>
            <div className={styles.container}>{children}</div>
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
